[package]
name = "path-sanitizer"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
std = []
alloc = []

[dependencies]

[dev-dependencies]
pretty_assertions = "0.6"
